const markersData = [
  {id:'vice-city',name:'Vice City',region:'Vice City',x:0,y:700,evidence:'official',confidence:'Nom officiel · placement estimé',desc:'La métropole néon de Leonida. Son existence est officielle ; sa forme, ses limites et son placement précis restent reconstruits.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'vice-beach',name:'Vice Beach',region:'Vice City',x:1750,y:1000,evidence:'community',confidence:'Placement triangulé',desc:'Façade océanique inspirée de Miami Beach, reconstruite grâce aux hôtels et immeubles reconnaissables dans les images officielles.',source:'https://github.com/rolux/gtadb.org'},
  {id:'downtown',name:'Downtown Vice City',region:'Vice City',x:-550,y:450,evidence:'community',confidence:'Forte confiance relative',desc:'Centre vertical de Vice City. Plusieurs tours récurrentes permettent de croiser les lignes de vue entre les scènes.',source:'https://www.reddit.com/r/GTA6/comments/1p8ow14/inside_gta_vi_mapping_the_community_rebuilding/'},
  {id:'airport',name:'Vice City International Airport',region:'Vice City',x:-2508,y:-520,evidence:'community',confidence:'Coordonnées communautaires',desc:'Le complexe aéroportuaire est placé à l’ouest de la ville à partir de hangars, de la tour de contrôle et des axes routiers visibles.',source:'https://github.com/rolux/gtadb.org'},
  {id:'jack-hearts',name:'Jack of Hearts',region:'Vice City',x:-686,y:1195,evidence:'community',confidence:'Repère identifié',desc:'Club de Crosstown associé à Boobie Ike dans les contenus officiels. La position est celle de la reconstruction GTADB.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'nine1nine',name:'NINE1NINE',region:'Vice City',x:-671,y:468,evidence:'community',confidence:'Repère identifié',desc:'Établissement du Downtown utilisé comme point de repère par les mappeurs.',source:'https://github.com/rolux/gtadb.org'},
  {id:'little-cuba',name:'Little Cuba',region:'Vice City',x:-1150,y:100,evidence:'community',confidence:'Quartier reconstruit',desc:'Secteur urbain à l’ouest du centre, identifié par recoupement des rues, enseignes et équivalents floridiens.',source:'https://github.com/rolux/gtadb.org'},
  {id:'keys',name:'Leonida Keys',region:'Leonida Keys',x:-2900,y:-6200,evidence:'official',confidence:'Nom officiel · contour estimé',desc:'Archipel officiellement présenté par Rockstar. La géométrie des îles et de l’Overseas Highway reste communautaire.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'jason-house',name:'Maison de Jason',region:'Leonida Keys',x:-2354,y:-5532,evidence:'leak',confidence:'Coordonnée issue de l’enquête',desc:'Point placé à partir des coordonnées et recoupements communautaires. Le site ne redistribue aucune image du leak.',source:'https://gtaforums.com/topic/985670-mapping-vice-city-map-discussion-thread-no-leak-footage-allowed/'},
  {id:'brian-marina',name:'Marina de Brian',region:'Leonida Keys',x:-2558,y:-5861,evidence:'community',confidence:'Repère identifié',desc:'La marina liée à Brian Heder, personnage officiellement présenté par Rockstar, est replacée ici selon GTADB.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'grassrivers',name:'Grassrivers',region:'Grassrivers',x:-3300,y:-4300,evidence:'official',confidence:'Nom officiel · limites estimées',desc:'Immense zone humide inspirée des Everglades, officiellement nommée par Rockstar.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'grass-center',name:'Grassrivers Visitor Center',region:'Grassrivers',x:-2665,y:-4761,evidence:'community',confidence:'Correspondance réelle',desc:'Centre d’accueil identifié par comparaison avec son équivalent floridien et replacé sur la carte communautaire.',source:'https://github.com/rolux/gtadb.org'},
  {id:'port-gellhorn',name:'Port Gellhorn',region:'Port Gellhorn',x:-6200,y:3200,evidence:'official',confidence:'Nom officiel · centre estimé',desc:'Ville portuaire officiellement révélée par Rockstar. Sa trame urbaine est reconstruite à partir des plans disponibles.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'raceway',name:'Gellhorn International Raceway',region:'Port Gellhorn',x:-6752,y:2298,evidence:'community',confidence:'Coordonnées GTADB',desc:'Circuit identifié dans la base collaborative de lieux et placé sur la reconstruction YANIS.',source:'https://github.com/rolux/gtadb.org'},
  {id:'ambrosia',name:'Ambrosia',region:'North Leonida',x:-2700,y:3900,evidence:'official',confidence:'Nom officiel · centre estimé',desc:'Ville industrielle officiellement nommée. Les silos et installations sucrières structurent sa reconstruction.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'sugar-mill',name:'Allied Crystal Sugar Mill',region:'North Leonida',x:-3017,y:3347,evidence:'community',confidence:'Repère industriel',desc:'Complexe industriel utilisé comme ancre visuelle pour Ambrosia.',source:'https://github.com/rolux/gtadb.org'},
  {id:'kalaga',name:'Mount Kalaga National Park',region:'North Leonida',x:-3430,y:6371,evidence:'official',confidence:'Nom officiel · étendue inconnue',desc:'Parc national officiellement présenté. Son relief exact et ses frontières ne sont pas publiés.',source:'https://www.rockstargames.com/VI/only-in-leonida'},
  {id:'penitentiary',name:'Leonida Penitentiary',region:'North Leonida',x:-2800,y:-2850,evidence:'leak',confidence:'Nom officiel · position communautaire',desc:'La prison est officielle dans l’histoire de Lucia ; sa position sur la carte repose sur les coordonnées et le travail communautaire.',source:'https://www.rockstargames.com/VI/only-in-leonida'}
];

const ranges={0:[[0,0],[3,3]],1:[[1,1],[6,6]],2:[[2,2],[12,12]],3:[[5,5],[25,24]],4:[[10,10],[51,49]]};
const stage=document.getElementById('mapStage'),canvas=document.getElementById('mapCanvas'),ctx=canvas.getContext('2d'),markersLayer=document.getElementById('markers');
let state={x:-2500,y:0,z:1.55,drag:false,lastX:0,lastY:0,region:'all',query:'',evidence:new Set(['official','community','leak']),selected:null};
const cache=new Map();

function fitCanvas(){const dpr=Math.min(devicePixelRatio||1,2),r=stage.getBoundingClientRect();canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);render()}
function transform(x,y){const size=1024*Math.pow(2,state.z),ppm=size/32768;return {x:stage.clientWidth/2+(x-state.x)*ppm,y:stage.clientHeight/2-(y-state.y)*ppm}}
function visibleMarkers(){return markersData.filter(m=>state.evidence.has(m.evidence)&&(state.region==='all'||m.region===state.region)&&(!state.query||`${m.name} ${m.region}`.toLowerCase().includes(state.query)))}
function tileImage(z,x,y){const key=`${z}/${y}/${x}`;if(cache.has(key))return cache.get(key);const img=new Image();img.onload=render;img.src=`assets/tiles/${z}/${z},${y},${x}.jpg`;cache.set(key,img);return img}
function renderMap(){const w=stage.clientWidth,h=stage.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#081713';ctx.fillRect(0,0,w,h);const zi=Math.max(0,Math.min(4,Math.ceil(state.z))),size=1024*Math.pow(2,state.z),ppm=size/32768,cx=(state.x+16384)*ppm,cy=(16384-state.y)*ppm,offsetX=w/2-cx,offsetY=h/2-cy,tileSize=256*Math.pow(2,state.z-zi),[[x0,y0],[x1,y1]]=ranges[zi];const minX=Math.max(x0,Math.floor(-offsetX/tileSize)),maxX=Math.min(x1,Math.ceil((w-offsetX)/tileSize)),minY=Math.max(y0,Math.floor(-offsetY/tileSize)),maxY=Math.min(y1,Math.ceil((h-offsetY)/tileSize));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const img=tileImage(zi,x,y);if(img.complete&&img.naturalWidth)ctx.drawImage(img,offsetX+x*tileSize,offsetY+y*tileSize,tileSize,tileSize)}}
function renderMarkers(){markersLayer.innerHTML='';visibleMarkers().forEach(m=>{const p=transform(m.x,m.y);if(p.x<-30||p.x>stage.clientWidth+30||p.y<-30||p.y>stage.clientHeight+30)return;const b=document.createElement('button');b.className=`marker ${m.evidence}${state.selected===m.id?' selected':''}`;b.style.left=p.x+'px';b.style.top=p.y+'px';b.setAttribute('aria-label',m.name);b.innerHTML=`<span class="marker-label">${m.name}</span>`;b.onclick=e=>{e.stopPropagation();selectMarker(m)};markersLayer.appendChild(b)})}
function render(){renderMap();renderMarkers();document.getElementById('zoomLabel').textContent=`ZOOM ${state.z.toFixed(1)}×`;document.getElementById('coordLabel').textContent=`X ${Math.round(state.x)} · Y ${Math.round(state.y)}`}
function selectMarker(m){state.selected=m.id;const card=document.getElementById('placeCard'),label={official:'NOM OFFICIEL',community:'RECONSTRUCTION',leak:'INDICE DU LEAK'}[m.evidence];document.getElementById('placeRegion').textContent=m.region.toUpperCase();document.getElementById('placeTitle').textContent=m.name;document.getElementById('placeDescription').textContent=m.desc;const badge=document.getElementById('placeEvidence');badge.textContent=label;badge.className=`evidence ${m.evidence}`;document.getElementById('placeConfidence').textContent=m.confidence;document.getElementById('placeSource').href=m.source;card.classList.add('open');renderMarkers()}
function zoom(delta){const old=state.z;state.z=Math.max(.25,Math.min(4,state.z+delta));if(old!==state.z)render()}
stage.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;state.lastY=e.clientY;stage.setPointerCapture(e.pointerId);stage.classList.add('dragging')});
stage.addEventListener('pointermove',e=>{if(!state.drag)return;const ppm=1024*Math.pow(2,state.z)/32768;state.x-=(e.clientX-state.lastX)/ppm;state.y+=(e.clientY-state.lastY)/ppm;state.lastX=e.clientX;state.lastY=e.clientY;render()});
stage.addEventListener('pointerup',()=>{state.drag=false;stage.classList.remove('dragging')});stage.addEventListener('pointercancel',()=>{state.drag=false;stage.classList.remove('dragging')});
stage.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?.22:-.22)},{passive:false});stage.addEventListener('click',()=>{state.selected=null;document.getElementById('placeCard').classList.remove('open');renderMarkers()});
document.getElementById('zoomIn').onclick=()=>zoom(.35);document.getElementById('zoomOut').onclick=()=>zoom(-.35);document.getElementById('resetMap').onclick=()=>{state.x=-2500;state.y=0;state.z=1.55;render()};document.getElementById('closeCard').onclick=e=>{e.stopPropagation();state.selected=null;document.getElementById('placeCard').classList.remove('open');renderMarkers()};

document.querySelectorAll('.check input').forEach(input=>input.addEventListener('change',()=>{input.checked?state.evidence.add(input.value):state.evidence.delete(input.value);renderMarkers();updateCounts()}));
document.querySelectorAll('.region').forEach(b=>b.onclick=()=>{document.querySelectorAll('.region').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.region=b.dataset.region;renderMarkers();if(innerWidth<900)document.getElementById('sidebar').classList.remove('open')});
document.getElementById('searchInput').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderMarkers()});
document.getElementById('resetFilters').onclick=()=>{state.evidence=new Set(['official','community','leak']);document.querySelectorAll('.check input').forEach(x=>x.checked=true);state.query='';document.getElementById('searchInput').value='';updateCounts();renderMarkers()};
function updateCounts(){['official','community','leak'].forEach(v=>{document.getElementById('count'+v[0].toUpperCase()+v.slice(1)).textContent=markersData.filter(m=>m.evidence===v).length})}updateCounts();

const views={map:document.getElementById('mapView'),investigation:document.getElementById('investigationView'),sources:document.getElementById('sourcesView')};
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');Object.values(views).forEach(v=>v.classList.remove('active-view'));views[b.dataset.view].classList.add('active-view');if(b.dataset.view==='map')setTimeout(fitCanvas,0)});
document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.add('open');document.getElementById('closeSidebar').onclick=()=>document.getElementById('sidebar').classList.remove('open');
window.addEventListener('resize',fitCanvas);fitCanvas();setTimeout(()=>selectMarker(markersData[0]),300);
